### ISSUE TITLE
Add blackboards in trace replay / iree-run-trace.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#12525]
A new blackboard stored on `iree_trace_replay_t` with string keyed variants would allow for traces to save results of calls to pass to subsequent calls.

Example:
```yaml
type: call
function: module.sqrt
args:
- !hal.buffer_view 1xf32=16
results:
- !blackboard.set temp_value
---
type: call
function: module.sqrt
args:
- !blackboard.get temp_value
results:
- !hal.buffer_view 1xf32=2
```

A utility of `!ignore` would make it easier to slice out only the relevant results:
```yaml
type: call
function: module.four_results
results:
- !ignore
- !blackboard.set result1
- !ignore
- !blackboard.set result3
```

The load macro should also support specifying move semantics to prevent the blackboard from leaking, possibly as a `!blackboard.take <key>`:
```yaml
type: call
function: module.sqrt
args:
- !blackboard.take temp_value
```
