### ISSUE TITLE
Add input/output events/macros to trace replay / iree-run-trace.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#12526]
Getting invocation dynamic I/O into trace replay is currently tricky. We can support both command line flags matching iree-run-module (`--input=` and `--output=`) and events that allow for programmatic I/O. This combines with #12525 by allowing loading/saving the blackboard contents.

Flag/list accessors for consuming/producing ala `--input=`/`--output=`:
```yaml
type: call
function: module.foo
args:
- !input.take 0
- !input.take 1
results:
- !output.set 0
- !output.set 1
```
`iree_trace_replay_t` would gain two optional lists for inputs/outputs and the macros would load/store from the lists. `iree-run-trace` can declare flags but other tools can programmatically control both lists.

For easier file IO without flag manipulation - useful for large weights/etc - we could also add some numpy events for loading/saving multiple blackboard values from a numpy file:
```yaml
type: numpy_load
path: input.npy
values:
- !blackboard.set input0
- !blackboard.set input1
```
And saving multiple blackboard values to a numpy file:
```yaml
type: numpy_save
path: output.npy
values:
- !blackboard.take result0
- !blackboard.take result1
```

In the future we could support pickled dicts and such if we wanted to do direct blackboard load/save.
