### ISSUE TITLE
Refactor GH Actions workflow files to use matrices

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#17136]
These can reduce boilerplate: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs. They do also change the presentation in the UI, for better or worse.

Places they could be useful:

ci.yml:
* `build_test_all_`: arm64, windows, macos_arm64, macos_x86_64, linux
* `build_test_runtime_`: arm64, windows, linux
* configurations: asan,tsan,small_runtime,gcc,tracing,debug,byo_llvm (some re-use possible?)
* cross_compile_and_test (linux riscv, generic riscv, emscripten): already used, but could rework the naming

pkgci.yml:
* regression test: CPU, AMDGPU-Vulkan, AMDGPU-ROCm, NVIDIAGPU-Vulkan, NVIDIAGPU-CUDA

Similar issues:
* https://github.com/iree-org/iree/issues/1156
* https://github.com/iree-org/iree/issues/1818

**Comment by ScottTodd** [comment]
For the "configurations" jobs, I want to try adding a CMake preset for each configuration here: https://github.com/iree-org/iree/tree/main/build_tools/cmake/presets then setting up a matrix like

```yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc
            runs-on: ubuntu-20.04
            container: ...
            preset: .../gcc.json
            configure: true
            build: true
            test: true
```

could then add some presets we want to test just the configure step. Tests enabled/disabled, samples enabled/disabled, all input plugins disabled, etc.

If we feel that generates too many jobs and clutters PRs with checks, we could have the job just run nightly on a schedule instead of on pull_request and push events.
