### ISSUE TITLE
Migrate lint checks to pre-commit?

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#17430]
## Current lint checks

We have a lint workflow and script, both of which require some manual setup and can get out of sync:
* https://github.com/iree-org/iree/blob/main/.github/workflows/lint.yml
* https://github.com/iree-org/iree/blob/main/build_tools/scripts/lint.sh

We currently run:

Tool | Description
-- | --
`bazel_to_cmake` | Our [custom tool](https://github.com/iree-org/iree/tree/main/build_tools/bazel_to_cmake) for translating BUILD.bazel files to CMakeLists.txt files
`buildifier` | Formatting BUILD.bazel files
`black` | Formatting Python files
`pytype` | Analyzing types in Python files<br>This has enough false positives to remove-- we could switch to mypy
`clang-format` | Formatting C/C++ files
`tabs` | Our [custom script](https://github.com/iree-org/iree/blob/main/build_tools/scripts/check_tabs.sh) to check source files tabs when spaces should be used
`yamllint` | Linting yaml files
`markdownlint` | Linting markdown files
`path_lengths` | Checking for long path lengths (problematic on Windows)
`generated_cmake_files` | Checking that our [test suite generation scripts](https://github.com/iree-org/iree/blob/main/build_tools/testing/generate_cmake_e2e_test_artifacts_suite.py) have been run
`build_file_names` | Checking that Bazel files are named `BUILD.bazel` instead of `BUILD`<br>Remove? Helps with integration into Google's downstream repo

## Pre-commit

[Pre-commit](https://pre-commit.com/) is "a multi-language package manager for pre-commit hooks" that can be run easily on developer machines (no need to separately install specific versions of each tool) and on GitHub Actions via either an [action](https://github.com/pre-commit/action) or a [service](https://pre-commit.ci/).

We've started using pre-commit on a few related projects and it has been helpful. See also this recent [discussion on Discord](https://discord.com/channels/689900678990135345/689906000043573354/1240766197008695377).

**Comment by ScottTodd** [comment]
We can also update our required status checks to block on all lint checks using this (or we could use the 'summary' style that ci.yml has. Right now we only block on clang-format, bazel_to_cmake, and yamllint:
![image](https://github.com/iree-org/iree/assets/4010439/d3648f83-aeeb-4cca-908d-b264cb012dd2)

**Comment by ScottTodd** [comment]
Tip for installing pre-commit: use pipx: https://packaging.python.org/en/latest/guides/installing-stand-alone-command-line-tools/

**Comment by ScottTodd** [comment]
Started testing this out in IREE with https://github.com/iree-org/iree/pull/17534 and this `.pre-commit-config.yaml` file:

```yml
exclude: "third_party/"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude_types: ["image", "jupyter"]
    -   id: check-yaml
        exclude: "mkdocs.yml"  # Extensions aren't included in the schema: https://github.com/squidfunk/mkdocs-material/issues/6378
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
```

So far I'm liking the ergonomics.

Setup on Windows:

```
py -m pip install --user pipx
py -m pipx ensurepath
pipx install pre-commit

pre-commit run --all-files
```
